logo: assets/brand/logo.svg

social:
  instagram: vectorvcinco
  email: itzelschiaffini@vectorvcinco.design
  facebook: vectorvcinco
  pinterest: vectorvcinco

links:
  store: https://store.vectorvcinco.design
  huertito: http://huertito.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: vectorvcinco/vectorvcinco-theme

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "all"
